### ISSUE TITLE
Module not working with dnd5e system version <=2

### ISSUE THREAD

**Issue by loginator** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#45] opened 2022-09-16 07:44 UTC
Since the dnd5e system was updated for foundry version 10. The module is not working anymore.
The problem seems to be the character and npc sheet resizing since those classes were moved inside of the system.
So basically the first 3 lines of code in the _dnd5e-de.js_ seem to be the issue:
```
// Foundry
import Actor from '../../systems/dnd5e/module/actor/sheets/character.js';
import NPC from '../../systems/dnd5e/module/actor/sheets/npc.js';
```
I tried to fix the issue myself but I never really got in touch with javascript and foundry development.

## Workaround
For anybody who's interrested in using the module with Foundry version 10 and the dnd5e system version.
Remove the following lines from the _dnd5e-de.js_:
```
// Foundry
import Actor from '../../systems/dnd5e/module/actor/sheets/character.js';
import NPC from '../../systems/dnd5e/module/actor/sheets/npc.js';
```
and
```
export class ActorSheet5eCharacter extends Actor {
  static get defaultOptions () {
    return mergeObject(super.defaultOptions, {
      classes: [module_sys, 'sheet', 'actor', 'character'],
      width: 800
    });
  }
}

export class ActorSheet5eNPC extends NPC {
  static get defaultOptions () {
    return mergeObject(super.defaultOptions, {
      classes: [module_sys, 'sheet', 'actor', 'npc'],
      width: 700
    });
  }
}
```
and
```
if (game.i18n.lang === module_lang &&
        game.system.id === module_sys &&
        game.settings.get(module_id, 'increaseSheetWidth')) {
        Actors.registerSheet(module_sys, ActorSheet5eCharacter, {
            types: ['character'],
            makeDefault: false
        });

        Actors.registerSheet(module_sys, ActorSheet5eNPC, {
            types: ['npc'],
            makeDefault: false
        });
    }
```
also remove the following lines from config.js (not required but the option is not usable anymore):
```
{
        name: 'increaseSheetWidth',
        data: {
            name: 'Breitere Charakterbögen',
            hint: 'Verbreitet die Charakterbögen. Kann bei abgeschnittenem Text helfen. (Bei Änderung wird Foundry neu geladen.)',
            scope: 'client',
            type: Boolean,
            config: true,
            default: false,
            onChange: () => window.location.reload()
        }
    },
```

If wanted i can create a pull request adding those changes but since this is removing the option to have bigger character sheets I'm not sure if that's wanted.

**Comment by w1ldv1b3z** [comment] 2022-09-25 10:16
Your Workaround only works for the GM-User.

Player`s still see only the english version of the SRD. Dragged Items/Spells/etc have to redragg by the GM-User.

**Comment by Niclasp1501** [comment] 2022-10-05 20:26
Thanks for the workaround, but I wonder when the developers will update to Foundry 10. Dear developers, please update the module for the new DnD system. Many Thanks

**Comment by SirMotte** [comment] 2022-10-12 16:43
Thank you very much for this. It's working now as intended. I'd like to add, that modules that rely on parsing text, for example the very useful [Foundry Meters, Grams and Liters](https://github.com/HadaIonut/Foundry-mgl) Module don't work anymore. An easy workaround is ofc to simply prep without the translation module active.

**Comment by 346184** [comment] 2022-10-22 23:24
Thanks for repoting. The module has been moved to a new repository, where this issue should be fixed.

**Closed as completed by 346184** 2022-10-22 23:24 UTC
